language: python
python:
  - "2.7"
env:
    - DJANGO_VERSION=1.4.10
    - DJANGO_VERSION=1.5.5
    - DJANGO_VERSION=1.6.1
    - BOTO_VERSION=2.22.0
    - BOTO_VERSION=2.20.0
    - BOTO_VERSION=2.15.0
    - BOTO_VERSION=2.5.0
    - BOTO_VERSION=2.0.0
install:
    - pip install -q nose django-nose Django==$DJANGO_VERSION boto==$BOTO_VERSION
    - pip install .

script: ./runtests.py
