language: python
python:
  - "2.7"
env:
    - DJANGO_VERSION=1.5.5
    - DJANGO_VERSION=1.6.1
install:
    - pip install -q nose django-nose mock Django==$DJANGO_VERSION
    - pip install .

script: ./runtests.py

after_success: coveralls
