language: python
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.4.10
python:
  - "2.7"
  - "3.3"
env:
    - DJANGO_VERSION=1.4.10
    - DJANGO_VERSION=1.5.5
    - DJANGO_VERSION=1.6.1
install:
    - pip install -q nose django-nose Django==$DJANGO_VERSION
    - pip install .

script: ./runtests.py
